import "../styles/globals.css";

import { Inter } from "next/font/google";
import ContactoBar from "@/components/Contact/ContactoBar";
import Logo from "@/components/logo";
import NavbarGuias from "@/components/navbarGuias";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Logo />
        <NavbarGuias />
        {children}
        <ContactoBar />
      </body>
    </html>
  );
}
